In [1]:
import numpy as np
import matplotlib.pylab as plt

In [4]:
x = np.array([-1, 1, 2])
print(x)
y = x > 0
y.astype(np.int)

[-1  1  2]


array([0, 1, 1])

In [5]:
def step_function(x):
    y = x > 0
    return y.astype(np.int)

In [6]:
step_function(x)

array([0, 1, 1])

In [7]:
# 시그모이드 함수 정의
def sigmoid_function(x):
    return 1 / (1 + np.exp(-x))

In [10]:
# 신경망 생성
def networks():
    ret = {}
    ret['W1'] = np.array([[0.1, 0.3, 0.5], [0.2, 0.4, 0.6]])
    ret['b1'] = np.array([0.1, 0.2, 0.3])
    ret['W2'] = np.array([[0.1, 0.4], [0.2, 0.5], [0.3, 0.6]])
    ret['b2'] = np.array([0.1, 0.2])
    ret['W3'] = np.array([[0.1, 0.3], [0.2, 0.4]])
    ret['b3'] = np.array([0.1, 0.2])
    return ret

def forward(network, x):
    W1, W2, W3 = network['W1'], network['W2'], network['W3']
    b1, b2, b3 = network['b1'], network['b2'], network['b3']
    
    a1 = np.dot(x, W1) + b1
    z1 = sigmoid_function(a1)
    a2 = np.dot(z1, W2) + b2
    z2 = sigmoid_function(a2)
    a3 = np.dot(z2, W3) + b3
    
    y = a3
    return y

In [11]:
network = networks()
x = np.array([1.0, 0.5])
y = forward(network, x)
print(y)

[0.31682708 0.69627909]
