In [2]:
import numpy as np

In [6]:
# 넘파이 배열 생성
A = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
B = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [4]:
print(A)
print(B)

[1 2 3 4 5 6 7 8 9]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [7]:
# 일정 step으로 증가하는 배열 생성
step = np.arange(0, 10, 1)
print(step)
step2 = np.arange(0, 1, 0.1)
print(step2)

[0 1 2 3 4 5 6 7 8 9]
[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9]


In [6]:
step.shape

(10,)

In [9]:
# 행렬 모양 바꾸기
step2.reshape(2, 5)

array([[0. , 0.1, 0.2, 0.3, 0.4],
       [0.5, 0.6, 0.7, 0.8, 0.9]])

In [10]:
# 영행렬 생성
zeromat = np.zeros((2, 2))
print(zeromat)

[[0. 0.]
 [0. 0.]]


In [11]:
# 단위행렬 생성
I = np.eye(4)
print(I)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [36]:
# 행렬 곱셈
I = np.eye(3)
A = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
A = A.reshape(3, 3)
M = np.dot(A, I)
print(M)

[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]


In [38]:
# 행렬 요소의 합
S = np.sum(A)
print(S)
# 각 행의 합
S2 = np.sum(A, axis=1)
#각 열의 합
S3 = np.sum(A, axis=0)
print(S2)
print(S3)
# 두 행렬 각 요소의 합
mat1 = np.array([7, 3, 1])
mat2 = np.array([6, 3, 9])
mat3 = mat1 + mat2
print(mat3)
# 두 행렬 각 요소의 곱
mat4 = mat1 * mat2
print(mat4)

45
[ 6 15 24]
[12 15 18]
[13  6 10]
[42  9  9]


In [8]:
# 랜덤값을 가지는 행렬 만들기
rndmat = np.random.rand(2, 3)
print(rndmat)

[[0.94280805 0.26292658 0.1253214 ]
 [0.86479623 0.55955821 0.34005442]]


In [9]:
rndmat.dtype

dtype('float64')

In [29]:
# 행렬에 내용 추가
A = np.arange(1, 10, 2)
print(A)
print(A.shape)
A = np.append(A, 11)
print(A)
print(A.shape)
A = np.append(A, [13, 15])
print(A)
B = [17, 19, 21]
A = np.append(A, B)
print(A)
print(A.shape)

[1 3 5 7 9]
(5,)
[ 1  3  5  7  9 11]
(6,)
[ 1  3  5  7  9 11 13 15]
[ 1  3  5  7  9 11 13 15 17 19 21]
(11,)


In [32]:
# 차분 벡터 구하기
diffvec = np.diff(A)
print(diffvec)
print(diffvec.shape)
diffvec2 = np.diff(diffvec)
diffvec3 = np.diff(A, n=2)
print(diffvec2)
print(diffvec3)

[2 2 2 2 2 2 2 2 2 2]
(10,)
[0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0]


In [34]:
# 행렬 쌓기
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
c = np.array([7, 8, 9])

v = np.vstack((a, b, c))
print(v)
co = np.column_stack((a, b, c))
print(co)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [40]:
# 행렬 일부만 따오기
tot = np.array([1, 5, 8, 11, 51, 67, 88, 91])
s1 = tot[1:3]
print(s1)
s2 = tot[0:3]
print(s2)

[5 8]
[1 5 8]


In [42]:
# 브로드캐스팅
K = 1
N = np.array([1, 3, 5, 7, 9])
print(K+N)
K = 2
print(K*N)

[ 2  4  6  8 10]
[ 2  6 10 14 18]
